

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
server.port=${PORT:8081}
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.path=/swagger-ui.html

# dhan
dhan.renew-url=https://api.dhan.co/v2/renewToken
dhan.partner-id=${DHAN_PARTNER_ID}
dhan.partner-secret=${DHAN_PARTNER_SECRET}
dhan.consent-id=${DHAN_CONSENT_ID}